name: Run tests

on:
  # run on push in master or rel_* branches excluding changes are only on doc or example folders
  push:
    branches:
      - master
      - "rel_*"
      # branches used to test the workflow
      - "workflow_test_*"
    paths-ignore:
      - "doc/**"
      - "examples/**"

env:
  # global env to all steps
  TOX_WORKERS: -n2

jobs:
  amd64-test:
    name: ${{ matrix.python-version }}-${{ matrix.build-type }}-${{ matrix.architecture }}-${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      # run this job using this matrix, excluding some combinations below.
      matrix:
        os:
          - "ubuntu-latest"
        python-version:
          - "2.7"
        build-type:
          - "cext"
        architecture:
          - x64

      fail-fast: false

    # steps to run in each job. Some are github actions, others run shell commands
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Set up python
        uses: actions/setup-python@v1
        with:
          python-version: ${{ matrix.python-version }}
          architecture: ${{ matrix.architecture }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install --upgrade tox setuptools
          pip list

      - name: Run tests
        run: tox -e github-${{ matrix.build-type }} -- -q --nomemory ${{ matrix.pytest-args }}
  arm64-test:
    name: Testing arm64-python3
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version:
          - "3.6"
      fail-fast: false
    steps:
      - uses: actions/checkout@v2
      - run: |
          docker run --rm --privileged hypriot/qemu-register
          docker run --name quayiopypamanylinux2014_aarch64_05103e --workdir /github/workspace --rm -e TOX_WORKERS -e INPUT_ARGS -v "/var/run/docker.sock":"/var/run/docker.sock" -v "/home/runner/work/_temp/_github_home":"/github/home" -v "/home/runner/work/_temp/_github_workflow":"/github/workflow" -v "/home/runner/work/sqlalchemy/sqlalchemy":"/github/workspace" quay.io/pypa/manylinux2014_aarch64 bash -c "uname -m"
